version: "3"

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5430:5432
    environment:
      - POSTGRESQL_USERNAME=apisolid
      - POSTGRESQL_PASSWORD=nodesolid
      - POSTGRESQL_DATABASE=api-node-solid
